import pandas as pd
import matplotlib.pyplot as plt
import os

# === 1. 读取数据 ===
print("📊 读取数据中...")
try:
    df = pd.read_csv("review_data.csv") # 确保这个文件名和你刚才生成的 CSV 一致
except FileNotFoundError:
    print("❌ 没找到 CSV 文件，请先运行 spider.py")
    exit()

# === 2. 数据清洗 ===
df['Price_Num'] = pd.to_numeric(df['价格'].astype(str).str.replace('$', '').str.replace(',', ''), errors='coerce')
df = df.dropna(subset=['Price_Num'])

# === 3. 画图 ===
plt.figure(figsize=(10, 6))
plt.rcParams['font.sans-serif'] = ['Arial Unicode MS'] 
plt.rcParams['axes.unicode_minus'] = False

colors = ['skyblue' if 'medicube' in name.lower() else 'lightgray' for name in df['标题']]
bars = plt.bar(df['ASIN'], df['Price_Num'], color=colors)

plt.title('Amazon Competitor Price Monitor', fontsize=16) # 用英文标题，防止网页乱码
plt.xlabel('ASIN', fontsize=12)
plt.ylabel('Price ($)', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.3)

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height, f'${height}', ha='center', va='bottom')

plt.tight_layout()

# === ⭐ 核心改变：保存为图片，而不是弹窗 ===
print("🖼️ 正在保存图表为 chart.png ...")
plt.savefig('chart.png') 

# === ⭐ 核心改变：生成 index.html 网页 ===
print("📝 正在生成 index.html ...")

html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Amazon Price Monitor</title>
    <style>
        body {{ font-family: sans-serif; text-align: center; padding: 50px; }}
        h1 {{ color: #333; }}
        img {{ max-width: 100%; height: auto; border: 1px solid #ddd; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.1); }}
        .timestamp {{ color: #888; margin-top: 20px; }}
    </style>
</head>
<body>
    <h1>Amazon Price Analysis Report</h1>
    <p>Latest Data from Python Bot</p>
    
    <img src="chart.png" alt="Price Chart">
    
    <p class="timestamp">Generated by Cursor Python Bot</p>
</body>
</html>
"""

# 写入 HTML 文件
with open("index.html", "w", encoding="utf-8") as f:
    f.write(html_content)

print("🎉 网页报告生成完毕！你可以双击 index.html 预览。")